version: "3"

services:
  app:
    command: ./wait-for-postgres.sh postgres .bin/app
    build:
      context: .
    ports:
      - "12001:80"
    environment:
      DB_DATABASE: pet_adoption_platform
      DB_USERNAME: test
      DB_PASSWORD: password

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pet_adoption_platform
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - "12000:5432"