version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - 12001:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: pet_adoption_platform
    ports:
      - 12000:27017
